-- Tab size for files
vim.cmd("autocmd BufRead,BufEnter *.astro set filetype=astro")
vim.cmd("autocmd FileType javascript setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd FileType typescript setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd FileType javascriptreact setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd FileType typescriptreact setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd FileType jsx setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd FileType tsx setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd FileType json setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd FileType html setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd FileType css setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd FileType nix setlocal shiftwidth=2 softtabstop=2 expandtab")
vim.cmd("autocmd BufWritePost *.tex silent! execute \"!xelatex % > /dev/null 2>&1\" ")
vim.cmd("autocmd FileType * set formatoptions-=cro")
