#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000

export EDITOR=nvim
export XDG_CONFIG_HOME="$HOME/.config/"

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.scripts:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

