#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000

export EDITOR=nvim
export XDG_CONFIG_HOME="$HOME/.config/"

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/Users/bytewaiser/.local/share/solana/install/active_release/bin:$PATH"
export PATH="/Users/bytewaiser/.deno/bin:$PATH"
export PATH="$PATH:/Users/bytewaiser/Library/Application Support/Coursier/bin"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

