#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/Users/bytewaiser/.local/share/solana/install/active_release/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
