#!/bin/sh
alias p="source $HOME/Programming/miniforge3/bin/activate;conda activate main"

alias ls=exa
alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # sh
